name: Check for updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Prepare Python
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r .github/scripts/requirements_check_update.txt

      - name: Check for updates
        run: |
          .venv/bin/python .github/scripts/check_update.py
